# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Event Log Plugin
description: Event Log Plugin
author: Yak.Works
group: org.grails.plugins

github:
  fullName: yakworks/grails-eventlog
git:
  releasableBranchRegex: master|release/.+
releaseNotes:
  file: docs/release-notes.md

team:
  developers: ['basejump: Joshua Burnett', 'alexeyzvegintcev: Alexey Zvegintcev']

bintray:
  enabled: true
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots

# using bash scripts to do`docs so disable in shipyak
docs:
  enabled: false
