# see defaults options https://github.com/yakworks/gradle-plugins/tree/master/src/main/resources/configs/defaults.yml
title: Event Log Plugin
description: Event Log Plugin
author: Yak.Works
group: yakworks.eventlog

github:
  fullName: yakworks/grails-event-log

team:
  developers: ['basejump: Joshua Burnett', 'alexeyzvegintcev: Alexey Zvegintcev']

bintray:
  enabled: true
  pkg:
    repo: grails-plugins
    userOrg: 9ci

maven:
  # repoUrl: http://repo.9ci.com/grails-plugins
  snapshotUrl: http://repo.9ci.com/oss-snapshots
